package com.jarvis.gymtracker.ui.screens.workout_session

/**
 * Curated exercise names used to fill up dropdown choices to 15 items per muscle group.
 */
private val exerciseCatalog: Map<String, List<String>> = mapOf(
    "chest" to listOf(
        "Barbell Bench Press",
        "Incline Barbell Bench Press",
        "Dumbbell Bench Press",
        "Incline Dumbbell Press",
        "Decline Bench Press",
        "Push-Up",
        "Weighted Push-Up",
        "Dips (Chest Lean)",
        "Cable Fly",
        "Incline Cable Fly",
        "Pec Deck Fly",
        "Machine Chest Press",
        "Single-Arm Cable Press",
        "Svend Press",
        "Landmine Press"
    ),
    "back" to listOf(
        "Deadlift",
        "Barbell Row",
        "Pendlay Row",
        "Single-Arm Dumbbell Row",
        "Seated Cable Row",
        "Chest-Supported Row",
        "T-Bar Row",
        "Lat Pulldown",
        "Pull-Up",
        "Chin-Up",
        "Straight-Arm Pulldown",
        "Inverted Row",
        "Meadows Row",
        "Machine Row",
        "Rack Pull"
    ),
    "lats" to listOf(
        "Wide-Grip Lat Pulldown",
        "Close-Grip Lat Pulldown",
        "Neutral-Grip Pulldown",
        "Single-Arm Lat Pulldown",
        "Pull-Up",
        "Assisted Pull-Up",
        "Straight-Arm Pulldown",
        "Kneeling Cable Pulldown",
        "Dumbbell Pullover",
        "Machine Pullover",
        "One-Arm Cable Row (Lat Bias)",
        "Underhand Pulldown",
        "Band Lat Pulldown",
        "Scapular Pull-Up",
        "Lat Prayer"
    ),
    "traps" to listOf(
        "Barbell Shrug",
        "Dumbbell Shrug",
        "Trap Bar Shrug",
        "Cable Shrug",
        "Behind-the-Back Barbell Shrug",
        "Upright Row",
        "High Pull",
        "Face Pull",
        "Farmer Carry",
        "Overhead Carry",
        "Snatch-Grip High Pull",
        "Rack Pull",
        "Prone Y-Raise",
        "Dumbbell Incline Shrug",
        "Kettlebell High Pull"
    ),
    "shoulders" to listOf(
        "Overhead Press",
        "Seated Dumbbell Press",
        "Arnold Press",
        "Push Press",
        "Lateral Raise",
        "Cable Lateral Raise",
        "Front Raise",
        "Rear Delt Fly",
        "Reverse Pec Deck",
        "Face Pull",
        "Machine Shoulder Press",
        "Landmine Shoulder Press",
        "Upright Row",
        "Dumbbell Cuban Press",
        "Leaning Lateral Raise"
    ),
    "rear delts" to listOf(
        "Reverse Pec Deck",
        "Bent-Over Rear Delt Fly",
        "Cable Rear Delt Fly",
        "Face Pull",
        "Chest-Supported Rear Delt Raise",
        "High Cable Row (Rear Delt)",
        "Band Pull-Apart",
        "Prone Rear Delt Raise",
        "Dumbbell Incline Rear Delt Fly",
        "Single-Arm Cable Rear Delt Fly",
        "Seated Rear Delt Fly",
        "Wide-Grip Face Pull",
        "Meadows Rear Delt Row",
        "Machine Rear Delt Fly",
        "Standing Rope Rear Delt Pull"
    ),
    "biceps" to listOf(
        "Barbell Curl",
        "EZ-Bar Curl",
        "Dumbbell Curl",
        "Incline Dumbbell Curl",
        "Hammer Curl",
        "Cable Curl",
        "Preacher Curl",
        "Concentration Curl",
        "Spider Curl",
        "Reverse Curl",
        "Bayesian Cable Curl",
        "Cross-Body Hammer Curl",
        "Drag Curl",
        "Machine Biceps Curl",
        "Chin-Up"
    ),
    "triceps" to listOf(
        "Triceps Pushdown",
        "Rope Pushdown",
        "Overhead Cable Extension",
        "Skull Crusher",
        "Close-Grip Bench Press",
        "Bench Dip",
        "Weighted Dip",
        "Dumbbell Overhead Extension",
        "Lying Dumbbell Extension",
        "Single-Arm Cable Pushdown",
        "Reverse-Grip Pushdown",
        "JM Press",
        "Kickback",
        "Machine Triceps Extension",
        "PJR Pullover"
    ),
    "forearms" to listOf(
        "Wrist Curl",
        "Reverse Wrist Curl",
        "Hammer Curl",
        "Reverse Curl",
        "Plate Pinch Hold",
        "Farmer Carry",
        "Behind-the-Back Wrist Curl",
        "Cable Wrist Curl",
        "Cable Reverse Curl",
        "Towel Pull-Up Hold",
        "Dead Hang",
        "Wrist Roller",
        "Zottman Curl",
        "Finger Curl",
        "Pronations and Supinations"
    ),
    "legs" to listOf(
        "Back Squat",
        "Front Squat",
        "Romanian Deadlift",
        "Leg Press",
        "Walking Lunge",
        "Bulgarian Split Squat",
        "Step-Up",
        "Leg Extension",
        "Leg Curl",
        "Hip Thrust",
        "Calf Raise",
        "Goblet Squat",
        "Hack Squat",
        "Sumo Deadlift",
        "Glute Bridge"
    ),
    "quads" to listOf(
        "Back Squat",
        "Front Squat",
        "Hack Squat",
        "Leg Press",
        "Leg Extension",
        "Bulgarian Split Squat",
        "Walking Lunge",
        "Reverse Lunge",
        "Step-Up",
        "Goblet Squat",
        "Sissy Squat",
        "Spanish Squat",
        "Cyclist Squat",
        "Smith Machine Squat",
        "Heels-Elevated Squat"
    ),
    "hamstrings" to listOf(
        "Romanian Deadlift",
        "Stiff-Leg Deadlift",
        "Good Morning",
        "Lying Leg Curl",
        "Seated Leg Curl",
        "Nordic Curl",
        "Glute-Ham Raise",
        "Single-Leg Romanian Deadlift",
        "Kettlebell Swing",
        "Cable Pull-Through",
        "Hip Hinge",
        "Swiss Ball Leg Curl",
        "Deficit Romanian Deadlift",
        "Machine Hamstring Curl",
        "Banded Leg Curl"
    ),
    "glutes" to listOf(
        "Hip Thrust",
        "Barbell Glute Bridge",
        "Romanian Deadlift",
        "Sumo Deadlift",
        "Bulgarian Split Squat",
        "Walking Lunge",
        "Step-Up",
        "Cable Kickback",
        "Frog Pump",
        "Single-Leg Hip Thrust",
        "Curtsy Lunge",
        "Reverse Hyperextension",
        "Kettlebell Swing",
        "Banded Lateral Walk",
        "45-Degree Back Extension"
    ),
    "calves" to listOf(
        "Standing Calf Raise",
        "Seated Calf Raise",
        "Leg Press Calf Raise",
        "Donkey Calf Raise",
        "Single-Leg Calf Raise",
        "Smith Machine Calf Raise",
        "Jump Rope",
        "Farmer Walk on Toes",
        "Box Jump",
        "Pogo Jumps",
        "Bent-Knee Calf Raise",
        "Tibialis Raise",
        "Sled Push",
        "Calf Raise Hold",
        "Toe-Elevated Calf Raise"
    ),
    "abs" to listOf(
        "Crunch",
        "Cable Crunch",
        "Hanging Knee Raise",
        "Hanging Leg Raise",
        "Reverse Crunch",
        "Decline Sit-Up",
        "Ab Wheel Rollout",
        "Plank",
        "Side Plank",
        "Russian Twist",
        "Dead Bug",
        "Mountain Climber",
        "V-Up",
        "Toe Touch Crunch",
        "Bicycle Crunch"
    ),
    "core" to listOf(
        "Plank",
        "Side Plank",
        "Pallof Press",
        "Dead Bug",
        "Bird Dog",
        "Hollow Body Hold",
        "Farmer Carry",
        "Suitcase Carry",
        "Ab Wheel Rollout",
        "Cable Wood Chop",
        "Medicine Ball Slam",
        "Turkish Get-Up",
        "Stir the Pot",
        "Mountain Climber",
        "Hanging Knee Raise"
    ),
    "lower back" to listOf(
        "Back Extension",
        "Romanian Deadlift",
        "Good Morning",
        "Superman",
        "Bird Dog",
        "Deadlift",
        "Rack Pull",
        "Reverse Hyperextension",
        "Hip Hinge",
        "Kettlebell Swing",
        "Cable Pull-Through",
        "Glute-Ham Raise",
        "Prone Back Extension Hold",
        "Single-Leg Romanian Deadlift",
        "Hyperextension"
    ),
    "adductors" to listOf(
        "Machine Hip Adduction",
        "Copenhagen Plank",
        "Sumo Squat",
        "Lateral Lunge",
        "Cossack Squat",
        "Side-Lying Hip Adduction",
        "Cable Hip Adduction",
        "Sliding Side Lunge",
        "Single-Leg Romanian Deadlift",
        "Curtsy Lunge",
        "Goblet Cossack Squat",
        "Banded Adductor Squeeze",
        "Wide-Stance Leg Press",
        "Frog Stretch Pulse",
        "Standing Adductor Lift"
    ),
    "abductors" to listOf(
        "Machine Hip Abduction",
        "Banded Lateral Walk",
        "Clamshell",
        "Side-Lying Hip Abduction",
        "Cable Hip Abduction",
        "Lateral Step-Up",
        "Curtsy Lunge",
        "Skater Squat",
        "Single-Leg Glute Bridge",
        "Fire Hydrant",
        "Monster Walk",
        "Lateral Band Walk",
        "Standing Hip Abduction",
        "Banded Squat Hold",
        "Lateral Lunge"
    ),
    "full body" to listOf(
        "Back Squat",
        "Deadlift",
        "Bench Press",
        "Overhead Press",
        "Pull-Up",
        "Barbell Row",
        "Walking Lunge",
        "Push-Up",
        "Kettlebell Swing",
        "Farmer Carry",
        "Thruster",
        "Burpee",
        "Clean and Press",
        "Turkish Get-Up",
        "Sled Push"
    ),
    "cardio" to listOf(
        "Treadmill Run",
        "Outdoor Run",
        "Stationary Bike",
        "Rowing Machine",
        "Elliptical",
        "Jump Rope",
        "Stair Climber",
        "Assault Bike",
        "Incline Walk",
        "Swimming",
        "Sled Push",
        "Mountain Climber",
        "Burpee Intervals",
        "Shadow Boxing",
        "High Knees"
    )
)

private val groupAliases: Map<String, String> = mapOf(
    "pecs" to "chest",
    "pectoral" to "chest",
    "pectoralis" to "chest",
    "delts" to "shoulders",
    "shoulder" to "shoulders",
    "rear delt" to "rear delts",
    "tricep" to "triceps",
    "bicep" to "biceps",
    "lat" to "lats",
    "trap" to "traps",
    "leg" to "legs",
    "ab" to "abs",
    "lower-back" to "lower back",
    "adductor" to "adductors",
    "abductor" to "abductors"
)

// User-preferred training split groups for dropdown autofill.
private val primarySupportedGroups: Set<String> = setOf(
    "legs",
    "shoulders",
    "biceps",
    "triceps",
    "forearms",
    "chest",
    "abs"
)

private fun normalizeGroup(value: String): String {
    return value.trim().lowercase().replace("_", " ").replace(Regex("\\s+"), " ")
}

fun curatedExercisesForMuscleGroup(rawMuscleGroup: String): List<String> {
    val normalized = normalizeGroup(rawMuscleGroup)
    val canonical = groupAliases[normalized] ?: normalized
    val direct = exerciseCatalog[canonical]
    if (canonical in primarySupportedGroups && direct != null && direct.size >= 15) {
        return direct.take(15)
    }

    // For non-primary/unknown groups, do not auto-fill unrelated entries.
    return emptyList()
}


